# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 09:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=8)),
                ('end_time', models.CharField(max_length=8)),
                ('duration', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Doctor')),
                (
                'patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.MyUser')),
            ],
        ),
    ]
