# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='confirmation',
            field=models.CharField(choices=[('1', 'awaiting'), ('2', 'not_confirmed'), ('3', 'confirmed')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
