# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0002_auto_20161223_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
