# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0003_expertise_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
