# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 06:46
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0005_auto_20161224_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttime',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='end_time',
            field=models.CharField(default=datetime.datetime(2017, 1, 1, 6, 46, 43, 569415, tzinfo=utc), max_length=8),
            preserve_default=False,
        ),
    ]
