# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 09:43
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=60)),
                ('year_diploma', models.CharField(blank=True, max_length=4, validators=[
                    django.core.validators.RegexValidator(message='year must be 4 digits', regex='([0-9]{4})')])),
                ('diploma', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=300)),
                ('office_phone_number', models.CharField(blank=True, max_length=11, validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '09999999999'.",
                        regex='^([0]{1})([0-9]{10})$')])),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '09999999999'. 11 digits allowed.",
                        regex='^([0]{1})([0-9]{10})$')])),
                ('national_code', models.CharField(blank=True, max_length=10, validators=[
                    django.core.validators.RegexValidator(message='national code must be 10 digits.',
                                                          regex='^([0-9]{10})$')])),
                ('is_doctor', models.BooleanField(default=False)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.MyUser'),
        ),
    ]
