# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 00:06
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('appointment', '0004_auto_20161223_1822'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.ForeignKey(default=datetime.datetime(2016, 12, 24, 0, 6, 18, 776948, tzinfo=utc),
                                    on_delete=django.db.models.deletion.CASCADE, to='appointment.Expertise'),
            preserve_default=False,
        ),
    ]
