# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lat_location',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lon_location',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
