# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 01:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_doctor_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Expertise'),
        ),
    ]
