# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_auto_20161224_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.ManyToManyField(to='user.Insurance'),
        ),
    ]
