# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 13:07
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_doctor_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contract',
            field=models.FileField(default=datetime.datetime(2016, 12, 31, 13, 7, 20, 785265, tzinfo=utc),
                                   upload_to='files'),
            preserve_default=False,
        ),
    ]
