# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_doctor_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contract',
            field=models.FileField(upload_to='contracts'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(
                message='شماره تلفن وارد شده باید 11 رقمی بوده و با صفر شروع شود و با ارقام انگلیسی باشد.',
                regex='^([0]{1})([0-9]{10})$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='year_diploma',
            field=models.CharField(blank=True, max_length=4, validators=[
                django.core.validators.RegexValidator(message='سال وارد شده باید 4 رقمی و با ارقام انگلیسی باشد.',
                                                      regex='([0-9]{4})')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, validators=[
                django.core.validators.RegexValidator(message='کدملی وارد شده باید 10 رقمی و با ارقام انگلیسی باشد.',
                                                      regex='^([0-9]{10})$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(
                message='شماره تلفن وارد شده باید 11 رقمی بوده و با صفر شروع شود و با ارقام انگلیسی باشد.',
                regex='^([0]{1})([0-9]{10})$')]),
        ),
    ]
