# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_auto_20170103_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
