# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0007_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='diploma',
            field=models.CharField(choices=[('عمومی', 'عمومی'), ('تخصص', 'تخصص'), ('فوق تخصص', 'فوق تخصص')],
                                   max_length=12),
        ),
    ]
